version: '3.8'
services:
  demo:
    build:
      context: .
      dockerfile: Dockerfile
    image: demo:latest
    container_name: demo
    ports:
      - '3001:3000'
    volumes:
      - .:/app
    environment:
      - MYSQL_HOST=${DB_HOST}
      - MYSQL_PORT=${DB_PORT}
      - MYSQL_USER=${DB_USERNAME}
      - MYSQL_PASSWORD=${DB_PASSWORD}
      - MYSQL_DATABASE=${DB_DATABASE}
    depends_on:
      - database
    networks:
      - demo-network

  database:
    image: mysql:8.0
    container_name: demo_mysql
    environment:
      MYSQL_ROOT_PASSWORD: ${DB_PASSWORD}
      MYSQL_DATABASE: ${DB_DATABASE}
      MYSQL_USER: ${DB_USERNAME}
      MYSQL_PASSWORD: ${DB_PASSWORD}
    ports:
      - '${DB_PORT}:3306'
    volumes:
      - db_data:/var/lib/mysql
    networks:
      - demo-network

volumes:
  db_data:

networks:
  demo-network:
